parallel-compiler = true

[alias]
xtask = "run --package xtask --"

# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]


# [build]
# rustflags = ["-Clink-arg=-fuse-ld=lld"]


