[package]
name = "tui-term-bench"
version = "0.0.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
bench = false

[dependencies]
tui-term = { path = ".." }
ratatui = { git = "https://github.com/tui-rs-revival/ratatui"}
